dictionaries = ["en_us"]
min_word_length = 3
words = [
    "actioned",
    "afca",
    "anytimefitness",
    "aspnetcore",
    "authorizers",
    "autodocs",
    "breakpoint",
    "buildmuscle",
    "ccw",
    "cdb",
    "cdk",
    "checkboxes",
    "classnames",
    "crowdin",
    "cva",
    "describedby",
    "dnd",
    "dynatrace",
    "entra",
    "exceljs",
    "fnm",
    "formatjs",
    "formatters",
    "fst",
    "ghostty",
    "gzip",
    "homebrew",
    "hotfixes",
    "htmli",
    "iam",
    "intl",
    "jsdom",
    "kampyle",
    "koji",
    "launchdarkly",
    "lucide",
    "luxon",
    "mbo",
    "medallia",
    "muuv",
    "noopener",
    "offcanvas",
    "oid",
    "omz",
    "orangetheory",
    "partialize",
    "pino",
    "reactstrap",
    "rollup",
    "rudderstack",
    "sbx",
    "seb",
    "shadcn",
    "sms",
    "sonner",
    "sourcetree",
    "spog",
    "spotify",
    "sso",
    "starship",
    "touchpoint",
    "touchpoints",
    "treeify",
    "uat",
    "utc",
    "vitest",
    "zellij",
    "zod",
    "zustand",
]
