dictionaries = ["en_us"]
words = [
    "CEB",
    "DTO",
    "FLYER",
    "Jira",
    "KEYFOB",
    "MCP",
    "NUL",
    "ONEPASSWORD",
    "RHF's",
    "UPN",
    "actioned",
    "afca",
    "anytimefitness",
    "aspnetcore",
    "authorizers",
    "autodocs",
    "birthdate",
    "breakpoint",
    "buildmuscle",
    "ccw",
    "cdb",
    "cdk",
    "checkboxes",
    "classnames",
    "cli",
    "crowdin",
    "cva",
    "describedby",
    "dnd",
    "dotenv",
    "dynatrace",
    "entra",
    "exceljs",
    "fnm",
    "formatjs",
    "formatters",
    "fst",
    "ghostty",
    "gzip",
    "herdr",
    "homebrew",
    "hotfixes",
    "htmli",
    "iam",
    "intl",
    "jsdom",
    "kampyle",
    "koji",
    "launchdarkly",
    "lazygit",
    "lifecycle",
    "lucide",
    "luxon",
    "mbms",
    "mbo",
    "medallia",
    "muuv",
    "noopener",
    "npmrc",
    "npx",
    "nvim",
    "nvm",
    "nvmrc",
    "offcanvas",
    "oid",
    "omz",
    "orangetheory",
    "partialize",
    "pino",
    "purposebrands",
    "reactstrap",
    "rollup",
    "rudderstack",
    "sbx",
    "seb",
    "shadcn",
    "sku",
    "sms",
    "sonner",
    "sourcetree",
    "spog",
    "spotify",
    "sso",
    "starship",
    "substatus",
    "toplevel",
    "touchpoint",
    "touchpoints",
    "treeify",
    "tsc",
    "uat",
    "utc",
    "vitest",
    "worktree",
    "worktrees",
    "zellij",
    "zod",
    "zustand",
]
min_word_length = 3
