onboarding = false

[theme]
name = "catppuccin"
auto_switch = false

[ui.toast]
delivery = "terminal"

[ui]
agent_panel_sort = "spaces"

[experimental]
kitty_graphics = true

[keys]
prefix = "alt+u"
rename_tab = ["prefix+shift+t", "prefix+comma"]
detach = ["prefix+q", "prefix+d"]
split_vertical = ["prefix+v", "prefix+backslash"]
split_horizontal = "prefix+minus"
workspace_picker = "prefix+w"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
previous_agent = "prefix+alt+k"
next_agent = "prefix+alt+j"
